apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  volumes:
    - name: vol
      hostPath:
        path: /etc/app/
  containers:
  - name: myapp-container
    image: devops-sig-app:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 8000
    volumeMounts:
      - name: vol
        mountPath: /etc/app/
  initContainers:
  - name: config-renderer
    image: config-renderer:latest
    command: ['sh', '-c', 'python /config_renderer.py']
    imagePullPolicy: Never
    envFrom:
      - configMapRef:
          name: configmap-myapp
    volumeMounts:
      - name: vol
        mountPath: /etc/app/
