apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  restartPolicy: Always
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  containers:
  - name: myapp-container
    image: devops-sig-app:latest
    imagePullPolicy: Never
    ports:
      - containerPort: 8000
    volumeMounts:
      - name: config-volume
        mountPath: /etc/app
    livenessProbe:
      exec:
        command: ['/config_update_check.py']
      initialDelaySeconds: 1
      periodSeconds: 2
      successThreshold: 1
      failureThreshold: 1